version: "3.9"
services:
  tomcat:
    container_name: tomcatExPrueba
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
  bd:
    image: mysql:8.2.0
    container_name: basededatosExPrueba
    environment:
      - MYSQL_ROOT_PASSWORD=miguedev
      - MYSQL_USER=migue
      - MYSQL_PASSWORD=miguedev
      - MYSQL_DATABASE=usuario
    volumes:
      - db-exPrueba2:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: tomcat_phpmyadminExPrueba
    environment:
      - PMA_HOST=bd
      - UPLOAD_LIMIT=300M
    ports:
      - "8083:80"
    volumes:
      - /sessions
    depends_on:
      - bd
volumes:
  db-exPrueba2: